<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FaturaTipi</name>
   <tag></tag>
   <elementGuidId>5aa0ccef-3c9a-43fb-8364-19868bf6a0c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div[1]/div/div[4]/div[1]/div/div/div[2]/div/form/div/div[1]/div/div[2]/div[1]/div/div/div/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div[1]/div/div[4]/div[1]/div/div/div[2]/div/form/div/div[1]/div/div[2]/div[1]/div/div/div/span[1]</value>
   </webElementProperties>
</WebElementEntity>
