<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FaturaTipiAd</name>
   <tag></tag>
   <elementGuidId>d0e839c8-d996-4d42-8dbb-ffe9de94c308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='reactRoot']/div[4]/div/div/div/div[2]/div/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='reactRoot']/div[4]/div/div/div/div[2]/div/div/div/div[3]/div</value>
      <webElementGuid>2ab64c7a-8d34-4a9e-bfeb-89ea68e4faa6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
