<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FaturaTipi</name>
   <tag></tag>
   <elementGuidId>5aa0ccef-3c9a-43fb-8364-19868bf6a0c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;rc_select_9&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;rc_select_9&quot;]</value>
      <webElementGuid>02dd9d76-752a-4cb8-9a62-377457d39508</webElementGuid>
   </webElementProperties>
</WebElementEntity>
