<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yeniEkle</name>
   <tag></tag>
   <elementGuidId>a453766a-b2a6-46cd-9d74-af93e925ba0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//vaadin-menu-bar-button[@ref_element = 'Object Repository/YeniEkranlar/ShadowKirilimlari/ThemeSecondry' and @ref_element_is_shadow_root = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>vaadin-menu-bar-button</value>
      <webElementGuid>ed260958-1cd2-40d2-9b42-aeb21c4b07bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/Tertiary</value>
      <webElementGuid>a39886d7-83c8-487b-9fbc-c70f38bc4640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42845810-5c6d-44fb-94f1-0301950bc732</webElementGuid>
   </webElementProperties>
</WebElementEntity>
