<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ComboBox</name>
   <tag></tag>
   <elementGuidId>bbbca05c-492e-4b29-a2ea-09c91f32a509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>logo-elements-combo-box</value>
      <webElementGuid>cab16c94-14c9-4db0-a3e0-071955e8c295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/ReactRoot</value>
      <webElementGuid>7621351d-5be2-48d3-b30f-49661f309438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df6ba378-0a8e-443c-a4e3-c584d364c0fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
