<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuBar</name>
   <tag></tag>
   <elementGuidId>9179b19d-18dd-4d9d-ada0-2bc863ffa947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//logo-elements-menu-bar[@ref_element = 'Object Repository/YeniEkranlar/Filtreler/ReactRoot' and @ref_element_is_shadow_root = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>logo-elements-menu-bar</value>
      <webElementGuid>8ef8b92c-1590-41a5-8263-7b0936a85f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/ReactRoot</value>
      <webElementGuid>76f5c2b1-f6df-4461-b975-7029737fd384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61f927e6-4df5-437a-b619-aef0556a8e0e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
