<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopupTamam</name>
   <tag></tag>
   <elementGuidId>836651f5-8a11-475e-9308-6f396a421cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;overlay&quot;]/vaadin-button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;overlay&quot;]/vaadin-button[3]</value>
      <webElementGuid>bee2d57a-5445-402c-9735-8ae982451629</webElementGuid>
   </webElementProperties>
</WebElementEntity>
