<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopupIptal</name>
   <tag></tag>
   <elementGuidId>4c4b3828-ddb0-4c4c-8780-402d05140d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;overlay&quot;]/vaadin-button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;overlay&quot;]/vaadin-button[1]</value>
      <webElementGuid>8b7d33d1-94db-4577-bba9-e4a367488948</webElementGuid>
   </webElementProperties>
</WebElementEntity>
