<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopupIcerigi</name>
   <tag></tag>
   <elementGuidId>acdf92cb-d0a8-478d-9b6a-2b7c39c0532b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>vaadin-notification-card</value>
      <webElementGuid>33c787ce-2f5a-427f-bdf9-a20156dc5794</webElementGuid>
   </webElementProperties>
</WebElementEntity>
