<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kdvMuhafiyetSecilir</name>
   <tag></tag>
   <elementGuidId>5ba55600-cd58-4278-9a80-a7c023639359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;react-select-5-option-0&quot;)/td[@class=&quot;ant-table-cell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-5-option-0&quot;)/td[@class=&quot;ant-table-cell&quot;]</value>
   </webElementProperties>
</WebElementEntity>
