<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aliciTablosu</name>
   <tag></tag>
   <elementGuidId>70a105a2-c539-40ce-a830-59eddf82acb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.ant-table-row.ant-table-row-level-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.ant-table-row.ant-table-row-level-0</value>
   </webElementProperties>
</WebElementEntity>
