<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ettnBilgisi</name>
   <tag></tag>
   <elementGuidId>6c342fb2-90ec-44fa-bc83-07f24c7123a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'Uuid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[2]/div/div[1]/div/div[1]/div[3]/form/div/div[1]/div/div[2]/div/div/input</value>
      <webElementGuid>875d22de-4847-4d2d-9312-41762b591fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Uuid</value>
      <webElementGuid>66309b58-3a01-43fd-b48d-04cf0380d2a8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
