<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FaturaTarihiBilgisi</name>
   <tag></tag>
   <elementGuidId>192b6a55-feb6-4d3c-a062-de351cd94678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'InvoiceDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[2]/div/div[1]/div/div[1]/div[3]/form/div/div[3]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>50042cdd-4e8b-40da-b4ba-ccccd57712d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InvoiceDate</value>
      <webElementGuid>74ca9bc3-7318-4d3d-8110-a14c855f593f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
