<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notlar</name>
   <tag></tag>
   <elementGuidId>2c7d898a-58d3-4b45-9f5c-a8223a6f4fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div[1]/div/div[12]/div[1]/div/div[1]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div[1]/div/div[12]/div[1]/div/div[1]/textarea</value>
   </webElementProperties>
</WebElementEntity>
