<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VknTcknGir</name>
   <tag></tag>
   <elementGuidId>72ceba52-7ea1-4d8a-9706-131e1ccd14ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[2]/div/div[2]/div/div[2]/div[2]/div/div/div[1]/div/div/div[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[2]/div/div[2]/div/div[2]/div[2]/div/div/div[1]/div/div/div[2]/span/input</value>
   </webElementProperties>
</WebElementEntity>
