<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AliciGirilir</name>
   <tag></tag>
   <elementGuidId>aa0ad160-ceb6-46d7-a5d6-b323ae8bb3e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'logo-elements-combo-box-11' and @ref_element = 'Object Repository/YeniEkranlar/ShadowKirilimlari/ComboBox' and @ref_element_is_shadow_root = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logo-elements-combo-box-11</value>
      <webElementGuid>39d69287-14d1-4792-93c4-97efd2aef645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/YeniEkranlar/ShadowKirilimlari/ReactRoot</value>
      <webElementGuid>73d5110a-0acc-435e-af22-40c538248012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2772e76e-d9d4-4de4-876c-e487cae10987</webElementGuid>
   </webElementProperties>
</WebElementEntity>
