<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GonderimSekli</name>
   <tag></tag>
   <elementGuidId>fca9a9fe-2f11-4d33-b69a-afa995e0b6e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'ProfileId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div[1]/div/div[1]/div[3]/form/div/div[4]/div/div[2]/div/div/div/div/span[2]</value>
      <webElementGuid>6a775a65-6aae-4d9f-b5d2-d9eb35f3f0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProfileId</value>
      <webElementGuid>d14e3ea3-9033-428c-bf19-53cbf6ff5cf1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
