<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ulke</name>
   <tag></tag>
   <elementGuidId>43c21293-9b49-45e5-8abb-6cda1afb053c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;rc_select_8&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;rc_select_8&quot;]</value>
      <webElementGuid>18145e87-3f58-4b1a-b6d1-8877b9bf1531</webElementGuid>
   </webElementProperties>
</WebElementEntity>
