<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OdemeSekli</name>
   <tag></tag>
   <elementGuidId>91af9ae5-fbf1-4482-aecf-8f792cf5f99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;rc_select_7&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;rc_select_7&quot;]</value>
      <webElementGuid>708e72f4-e680-4329-8a0a-59064cbe9a83</webElementGuid>
   </webElementProperties>
</WebElementEntity>
