<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OdemeSekli</name>
   <tag></tag>
   <elementGuidId>91af9ae5-fbf1-4482-aecf-8f792cf5f99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div[1]/div/div[6]/div/div/div/div[2]/div/form/div/div[1]/div/div[2]/div[1]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reactRoot&quot;]/div[1]/div/div[1]/div/div[6]/div/div/div/div[2]/div/form/div/div[1]/div/div[2]/div[1]/div/div</value>
   </webElementProperties>
</WebElementEntity>
